add deploy_resources

diff --git a/.github/workflows/on_pr_approved.yml b/.github/workflows/on_pr_approved.yml
--- a/.github/workflows/on_pr_approved.yml
+++ b/.github/workflows/on_pr_approved.yml
@@ -43,7 +43,7 @@ jobs:
       - name: Do something
         run: exit 1
 
-  # Only run if previous step failed
+  # Only run if previous step failed - always exit 1 to show the fail in the PR as failed
   deploy-tf-dev-from-develop:
     if: ${{ needs.check_condition.outputs.tf_related == 'true' && failure() }}
     needs: [check_condition, deploy-tf-dev]
@@ -53,6 +53,9 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
       - name: do stuff
-        run: gh workflow run deploy_aws_branch.yml --ref main --raw-field run-DBT-Docker-Step-flag=true
+        run: |
+          gh workflow run deploy_aws_branch.yml --ref main --raw-field run-DBT-Docker-Step-flag=true
+          echo "***** TF deployed to DEV successfully from develop *****"
+          exit 1
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
